# Generated by Django 3.2 on 2021-04-25 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTeller',
            fields=[
                ('bank_teller_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('id_number', models.CharField(max_length=30, unique=True)),
                ('deposit', models.FloatField()),
                ('bank_teller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.bankteller')),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=10, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('issue_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('loan_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.FloatField()),
                ('current_deposit', models.FloatField()),
                ('repay_cycle', models.IntegerField()),
                ('due_date', models.DateField()),
                ('next_overdue_date', models.DateField()),
                ('left_payment', models.FloatField()),
                ('left_fine', models.FloatField()),
                ('created_time', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RegularDeposit',
            fields=[
                ('regular_deposit_id', models.AutoField(primary_key=True, serialize=False)),
                ('regular_deposit_name', models.CharField(max_length=10, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('return_cycle', models.IntegerField()),
                ('return_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=10, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('issue_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('price', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockInvestmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_share', models.IntegerField()),
                ('purchase_amount', models.FloatField()),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('current_deposit', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.customer')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_share', models.IntegerField()),
                ('cumulative_purchase_amount', models.FloatField()),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('current_deposit', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.customer')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.stock')),
            ],
        ),
        migrations.CreateModel(
            name='RegularDepositInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_amount', models.FloatField()),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('current_deposit', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.customer')),
                ('regular_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.regulardeposit')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepay',
            fields=[
                ('repay_id', models.AutoField(primary_key=True, serialize=False)),
                ('left_payment_before', models.FloatField()),
                ('left_fine_before', models.FloatField()),
                ('repay', models.FloatField()),
                ('repay_time', models.DateField(default=django.utils.timezone.now)),
                ('current_deposit', models.FloatField()),
                ('loan_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.loanrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FundPriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('price', models.FloatField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.fund')),
            ],
        ),
        migrations.CreateModel(
            name='FundInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_share', models.FloatField()),
                ('purchase_amount', models.FloatField()),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('current_deposit', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.customer')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.fund')),
            ],
        ),
        migrations.CreateModel(
            name='DepositRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateField(default=django.utils.timezone.now)),
                ('payment', models.FloatField()),
                ('current_deposit', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.customer')),
            ],
        ),
    ]
