# Generated by Django 3.2 on 2021-04-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankteller',
            name='account',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='left_fine',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='left_payment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loanrepay',
            name='left_fine_before',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loanrepay',
            name='left_payment_before',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regulardeposit',
            name='regular_deposit_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
