# Generated by Django 3.2 on 2021-04-11 02:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0002_auto_20210410_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrecord',
            old_name='record_id',
            new_name='loan_record_id',
        ),
        migrations.RenameField(
            model_name='loanrepay',
            old_name='record_id',
            new_name='loan_record_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_teller_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bts.bankteller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='next_overdue_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regulardepositinvestment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fundpricerecord',
            name='record_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='payment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loanrepay',
            name='repay',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loanrepay',
            name='repay_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='regulardepositinvestment',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockinvestment',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockpricerecord',
            name='record_date',
            field=models.DateField(),
        ),
    ]
