# Generated by Django 3.2 on 2021-04-11 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0004_auto_20210411_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundinvestment',
            old_name='cumulative_purchase_amount',
            new_name='purchase_amount',
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='regulardepositinvestment',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockinvestment',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
