# Generated by Django 3.2 on 2021-04-11 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0006_auto_20210411_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrecord',
            name='created_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='created_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loanrepay',
            name='repay_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
