# Generated by Django 3.2 on 2021-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0007_auto_20210411_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrecord',
            name='current_deposit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='current_deposit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrepay',
            name='current_deposit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
