# Generated by Django 3.2 on 2021-04-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0008_auto_20210412_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestment',
            name='current_deposit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regulardepositinvestment',
            name='current_deposit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinvestment',
            name='current_deposit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
