# Generated by Django 3.2 on 2021-04-13 06:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0009_auto_20210412_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInvestmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_share', models.IntegerField()),
                ('purchase_amount', models.FloatField()),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('current_deposit', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.customer')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.stock')),
            ],
        ),
    ]
